ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_REALTIME_URL
ARG NEXT_PUBLIC_REALTIME_SOCKET_PATH=""
ARG NEXT_PUBLIC_REALTIME_DEBUG=""
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=""
ARG NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID=""
ARG NEXT_PUBLIC_DEFAULT_SCHOOL_ID=""
ARG NEXT_PUBLIC_MOBILE_APP_STUDENT_GOOGLE_PLAY_URL=""
ARG NEXT_PUBLIC_MOBILE_APP_STUDENT_APP_STORE_URL=""
ARG NEXT_PUBLIC_MOBILE_APP_TEACHER_GOOGLE_PLAY_URL=""
ARG NEXT_PUBLIC_MOBILE_APP_TEACHER_APP_STORE_URL=""
ARG NEXT_PUBLIC_MOBILE_APP_PARENT_GOOGLE_PLAY_URL=""
ARG NEXT_PUBLIC_MOBILE_APP_PARENT_APP_STORE_URL=""
ARG NEXT_PUBLIC_MOBILE_APP_DISMISSAL_STAFF_GOOGLE_PLAY_URL=""
ARG NEXT_PUBLIC_MOBILE_APP_DISMISSAL_STAFF_APP_STORE_URL=""

FROM node:22.23.1-bookworm-slim AS builder

WORKDIR /app

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_REALTIME_URL
ARG NEXT_PUBLIC_REALTIME_SOCKET_PATH
ARG NEXT_PUBLIC_REALTIME_DEBUG
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID
ARG NEXT_PUBLIC_DEFAULT_SCHOOL_ID
ARG NEXT_PUBLIC_MOBILE_APP_STUDENT_GOOGLE_PLAY_URL
ARG NEXT_PUBLIC_MOBILE_APP_STUDENT_APP_STORE_URL
ARG NEXT_PUBLIC_MOBILE_APP_TEACHER_GOOGLE_PLAY_URL
ARG NEXT_PUBLIC_MOBILE_APP_TEACHER_APP_STORE_URL
ARG NEXT_PUBLIC_MOBILE_APP_PARENT_GOOGLE_PLAY_URL
ARG NEXT_PUBLIC_MOBILE_APP_PARENT_APP_STORE_URL
ARG NEXT_PUBLIC_MOBILE_APP_DISMISSAL_STAFF_GOOGLE_PLAY_URL
ARG NEXT_PUBLIC_MOBILE_APP_DISMISSAL_STAFF_APP_STORE_URL

RUN if [ -z "${NEXT_PUBLIC_API_URL}" ]; then echo "NEXT_PUBLIC_API_URL build argument is required." >&2; exit 1; fi
RUN if [ -z "${NEXT_PUBLIC_REALTIME_URL}" ]; then echo "NEXT_PUBLIC_REALTIME_URL build argument is required." >&2; exit 1; fi

ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL} \
    NEXT_PUBLIC_REALTIME_URL=${NEXT_PUBLIC_REALTIME_URL} \
    NEXT_PUBLIC_REALTIME_SOCKET_PATH=${NEXT_PUBLIC_REALTIME_SOCKET_PATH} \
    NEXT_PUBLIC_REALTIME_DEBUG=${NEXT_PUBLIC_REALTIME_DEBUG} \
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY} \
    NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID=${NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID} \
    NEXT_PUBLIC_DEFAULT_SCHOOL_ID=${NEXT_PUBLIC_DEFAULT_SCHOOL_ID} \
    NEXT_PUBLIC_MOBILE_APP_STUDENT_GOOGLE_PLAY_URL=${NEXT_PUBLIC_MOBILE_APP_STUDENT_GOOGLE_PLAY_URL} \
    NEXT_PUBLIC_MOBILE_APP_STUDENT_APP_STORE_URL=${NEXT_PUBLIC_MOBILE_APP_STUDENT_APP_STORE_URL} \
    NEXT_PUBLIC_MOBILE_APP_TEACHER_GOOGLE_PLAY_URL=${NEXT_PUBLIC_MOBILE_APP_TEACHER_GOOGLE_PLAY_URL} \
    NEXT_PUBLIC_MOBILE_APP_TEACHER_APP_STORE_URL=${NEXT_PUBLIC_MOBILE_APP_TEACHER_APP_STORE_URL} \
    NEXT_PUBLIC_MOBILE_APP_PARENT_GOOGLE_PLAY_URL=${NEXT_PUBLIC_MOBILE_APP_PARENT_GOOGLE_PLAY_URL} \
    NEXT_PUBLIC_MOBILE_APP_PARENT_APP_STORE_URL=${NEXT_PUBLIC_MOBILE_APP_PARENT_APP_STORE_URL} \
    NEXT_PUBLIC_MOBILE_APP_DISMISSAL_STAFF_GOOGLE_PLAY_URL=${NEXT_PUBLIC_MOBILE_APP_DISMISSAL_STAFF_GOOGLE_PLAY_URL} \
    NEXT_PUBLIC_MOBILE_APP_DISMISSAL_STAFF_APP_STORE_URL=${NEXT_PUBLIC_MOBILE_APP_DISMISSAL_STAFF_APP_STORE_URL}

COPY package.json package-lock.json ./
COPY scripts/setup-fonts.js ./scripts/setup-fonts.js
RUN npm ci

COPY . .
RUN npm run build

FROM node:22.23.1-bookworm-slim AS runner

WORKDIR /app

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_REALTIME_URL
ARG NEXT_PUBLIC_REALTIME_SOCKET_PATH
ARG NEXT_PUBLIC_REALTIME_DEBUG
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID
ARG NEXT_PUBLIC_DEFAULT_SCHOOL_ID
ARG NEXT_PUBLIC_MOBILE_APP_STUDENT_GOOGLE_PLAY_URL
ARG NEXT_PUBLIC_MOBILE_APP_STUDENT_APP_STORE_URL
ARG NEXT_PUBLIC_MOBILE_APP_TEACHER_GOOGLE_PLAY_URL
ARG NEXT_PUBLIC_MOBILE_APP_TEACHER_APP_STORE_URL
ARG NEXT_PUBLIC_MOBILE_APP_PARENT_GOOGLE_PLAY_URL
ARG NEXT_PUBLIC_MOBILE_APP_PARENT_APP_STORE_URL
ARG NEXT_PUBLIC_MOBILE_APP_DISMISSAL_STAFF_GOOGLE_PLAY_URL
ARG NEXT_PUBLIC_MOBILE_APP_DISMISSAL_STAFF_APP_STORE_URL

ENV NODE_ENV=production \
    PORT=8080 \
    HOSTNAME=0.0.0.0 \
    NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL} \
    NEXT_PUBLIC_REALTIME_URL=${NEXT_PUBLIC_REALTIME_URL} \
    NEXT_PUBLIC_REALTIME_SOCKET_PATH=${NEXT_PUBLIC_REALTIME_SOCKET_PATH} \
    NEXT_PUBLIC_REALTIME_DEBUG=${NEXT_PUBLIC_REALTIME_DEBUG} \
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY} \
    NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID=${NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID} \
    NEXT_PUBLIC_DEFAULT_SCHOOL_ID=${NEXT_PUBLIC_DEFAULT_SCHOOL_ID} \
    NEXT_PUBLIC_MOBILE_APP_STUDENT_GOOGLE_PLAY_URL=${NEXT_PUBLIC_MOBILE_APP_STUDENT_GOOGLE_PLAY_URL} \
    NEXT_PUBLIC_MOBILE_APP_STUDENT_APP_STORE_URL=${NEXT_PUBLIC_MOBILE_APP_STUDENT_APP_STORE_URL} \
    NEXT_PUBLIC_MOBILE_APP_TEACHER_GOOGLE_PLAY_URL=${NEXT_PUBLIC_MOBILE_APP_TEACHER_GOOGLE_PLAY_URL} \
    NEXT_PUBLIC_MOBILE_APP_TEACHER_APP_STORE_URL=${NEXT_PUBLIC_MOBILE_APP_TEACHER_APP_STORE_URL} \
    NEXT_PUBLIC_MOBILE_APP_PARENT_GOOGLE_PLAY_URL=${NEXT_PUBLIC_MOBILE_APP_PARENT_GOOGLE_PLAY_URL} \
    NEXT_PUBLIC_MOBILE_APP_PARENT_APP_STORE_URL=${NEXT_PUBLIC_MOBILE_APP_PARENT_APP_STORE_URL} \
    NEXT_PUBLIC_MOBILE_APP_DISMISSAL_STAFF_GOOGLE_PLAY_URL=${NEXT_PUBLIC_MOBILE_APP_DISMISSAL_STAFF_GOOGLE_PLAY_URL} \
    NEXT_PUBLIC_MOBILE_APP_DISMISSAL_STAFF_APP_STORE_URL=${NEXT_PUBLIC_MOBILE_APP_DISMISSAL_STAFF_APP_STORE_URL}

COPY --from=builder --chown=node:node /app/package.json ./package.json
COPY --from=builder --chown=node:node /app/next.config.ts ./next.config.ts
COPY --from=builder --chown=node:node /app/tsconfig.json ./tsconfig.json
COPY --from=builder --chown=node:node /app/public ./public
COPY --from=builder --chown=node:node /app/.next ./.next
COPY --from=builder --chown=node:node /app/node_modules ./node_modules

USER node

EXPOSE 8080

CMD ["npm", "run", "start", "--", "--hostname", "0.0.0.0"]
